version: "2"

services:
    alpine-cron:
      build:
        context: alpine-cron
        dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
        - /etc/localtime:/etc/localtime:ro
 
